#!/bin/bash

get_volume() {
    pactl get-sink-volume @DEFAULT_SINK@ | grep -Po '\d+(?=%)' | head -1
}

get_mute() {
    pactl get-sink-mute @DEFAULT_SINK@ | grep -o "yes"
}

case $1 in
    up)
        pactl set-sink-mute @DEFAULT_SINK@ 0
        pactl set-sink-volume @DEFAULT_SINK@ +5%
        ;;
    down)
        pactl set-sink-mute @DEFAULT_SINK@ 0
        pactl set-sink-volume @DEFAULT_SINK@ -5%
        ;;
    mute)
        pactl set-sink-mute @DEFAULT_SINK@ toggle
        ;;
esac

volume=$(get_volume)
mute=$(get_mute)

if [ "$mute" = "yes" ]; then
    icon="audio-volume-muted"
    text="Muted"
else
    if [ "$volume" -gt "70" ]; then
        icon="audio-volume-high"
    elif [ "$volume" -gt "30" ]; then
        icon="audio-volume-medium"
    else
        icon="audio-volume-low"
    fi
    text="Volume: $volume%"
fi

#dunstify -a "changevolume" -u low -i "$icon" -h int:value:"$volume" -h string:x-dunst-stack-tag:volume "$text" -t 1500
